sonar.projectKey=salah77712_saqynrabt
sonar.organization=salah77712
sonar.host.url=https://sonarcloud.io
sonar.projectBaseDir=.
sonar.sources=frontend,backend-workers
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/.wrangler/**
