export interface CaseStudy {
  slug: string;
  industry: string;
  title: string;
  result: string;
  challenge: string;
  solution: string;
  impact: string;
  metrics: string[];
  iconName: string;
  flag: string;
  location: string;
  meta: string;
}

export const cases = {
  en: [
    {
      slug: 'hotel-doha',
      industry: 'Hospitality',
      title: 'Hotel Front-Desk Call Automation',
      result: 'AI voice agent answers guest calls, handles late check-in requests, and routes complaints to the right department.',
      challenge: 'Hotels receive high volumes of calls about bookings, room service, and directions. Front-desk staff spend most of their shift on the phone instead of serving in-person guests.',
      solution: 'SAQYN RABT voice agent answers incoming calls, collects guest context, and either resolves the request or routes it to the relevant department.',
      impact: 'Front-desk staff spend less time on routine calls. Guests get faster answers, and the hotel handles more inquiries without adding headcount.',
      metrics: ['Reduced phone workload', '24/7 call coverage', 'Multi-language support'],
      iconName: 'Hotel',
      flag: '🇶🇦',
      location: 'Doha, Qatar',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'clinic-dubai',
      industry: 'Healthcare',
      title: 'Clinic Appointment Scheduling',
      result: 'AI handles booking inquiries, triages urgent cases, and routes prescription refill requests to the pharmacy.',
      challenge: 'Medical receptionists spend significant time on the phone answering scheduling questions, reducing time available for in-person patient care.',
      solution: 'Integrated an AI voice assistant that schedules appointments, answers FAQs about doctor availability, and routes urgent cases.',
      impact: 'More appointment slots filled, reduced phone wait times, and medical staff focus on clinical work.',
      metrics: ['Faster appointment booking', 'Reduced missed calls', 'Quick triage of urgent cases'],
      iconName: 'Activity',
      flag: '🇦🇪',
      location: 'Dubai, UAE',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'hvac-kuwait',
      industry: 'Home Services',
      title: 'HVAC After-Hours Emergency Response',
      result: 'Emergency repair calls are answered by AI, technician dispatch is triggered automatically.',
      challenge: 'Home service companies lose business when after-hours emergency calls go unanswered or get missed during peak seasons.',
      solution: 'AI voice agent answers calls 24/7, captures the issue details and location, and dispatches a technician automatically.',
      impact: 'Zero missed after-hours calls. Faster dispatch times and improved customer satisfaction during emergencies.',
      metrics: ['24/7 call capture', 'Automated dispatch', 'Reduced missed revenue'],
      iconName: 'Wrench',
      flag: '🇰🇼',
      location: 'Kuwait City, Kuwait',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'realestate-riyadh',
      industry: 'Real Estate',
      title: 'Property Inquiry Qualification',
      result: 'AI answers buyer inquiries, captures preferences, and schedules viewings with agents.',
      challenge: 'Property inquiries arrive via phone and WhatsApp throughout the day. Slow response times cause potential buyers to lose interest.',
      solution: 'AI assistant answers inquiries instantly, asks qualifying questions about budget and preferences, and books viewings on agent calendars.',
      impact: 'Faster lead response, better qualification before agent involvement, and more viewings booked.',
      metrics: ['Instant inquiry response', 'Lead qualification', 'Automated viewing scheduling'],
      iconName: 'Home',
      flag: '🇸🇦',
      location: 'Riyadh, KSA',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'ecommerce-abudhabi',
      industry: 'E-commerce',
      title: 'WhatsApp Order Support Automation',
      result: 'Customers check order status, request returns, and get shipping updates via an automated WhatsApp assistant.',
      challenge: 'Order tracking and return requests overwhelm the support team, causing delayed responses and customer frustration.',
      solution: 'Connected an AI assistant to the order management system via WhatsApp Business API to handle common queries automatically.',
      impact: 'Support team handles fewer routine queries. Customers get instant answers about their orders at any time.',
      metrics: ['Automated order tracking', 'Instant status updates', '24/7 customer support'],
      iconName: 'ShoppingBag',
      flag: '🇦🇪',
      location: 'Abu Dhabi, UAE',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'logistics-alrayyan',
      industry: 'Logistics',
      title: 'Delivery Status Self-Service',
      result: 'Customers check delivery status, reschedule pickups, and correct addresses through an automated assistant.',
      challenge: 'Delivery companies receive high volumes of calls about shipment status and address corrections, straining the support team.',
      solution: 'Implemented a self-service assistant that integrates with the tracking system to provide real-time updates and handle address changes.',
      impact: 'Support team workload reduced. Customers get instant answers without waiting on hold.',
      metrics: ['Self-service queries', 'Reduced support calls', 'Address verification'],
      iconName: 'Truck',
      flag: '🇶🇦',
      location: 'Al Rayyan, Qatar',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'legal-manama',
      industry: 'Legal Services',
      title: 'Legal Intake Qualification',
      result: 'AI screens potential clients, captures case details, and books consultations with the right attorney.',
      challenge: 'Law firms receive many intake calls after hours. Missed calls mean lost potential clients who call competitors.',
      solution: 'Secure intake assistant answers calls 24/7, screens practice area needs, and books consultations.',
      impact: 'More intake calls captured, attorneys only spend time on qualified leads, no missed potential clients.',
      metrics: ['After-hours call capture', 'Intake qualification', 'Automated consultation scheduling'],
      iconName: 'Briefcase',
      flag: '🇧🇭',
      location: 'Manama, Bahrain',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'rental-muscat',
      industry: 'Automotive',
      title: 'Car Rental Booking Automation',
      result: 'AI processes rental requests, verifies driver details, and confirms bookings automatically.',
      challenge: 'Car rental counters face long queues during peak tourist seasons. Paperwork and phone inquiries slow down service.',
      solution: 'AI assistant handles booking inquiries, captures driver license and passport details, and confirms reservations.',
      impact: 'Faster counter service, reduced phone inquiries, and more bookings handled without additional staff.',
      metrics: ['Automated booking process', 'Faster counter service', 'Digital documentation'],
      iconName: 'Car',
      flag: '🇴🇲',
      location: 'Muscat, Oman',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'education-jeddah',
      industry: 'Education',
      title: 'Student Inquiry Automation',
      result: 'AI answers schedule queries, course information requests, and manages student onboarding.',
      challenge: 'Administrative staff spend hours answering repetitive questions about schedules, courses, and enrollment procedures.',
      solution: 'Deployed a campus assistant that answers FAQs about class schedules, course materials, and registration.',
      impact: 'Admin staff focus on higher-value tasks. Students get instant answers to common questions outside office hours.',
      metrics: ['FAQ automation', 'After-hours support', 'Reduced admin calls'],
      iconName: 'GraduationCap',
      flag: '🇸🇦',
      location: 'Jeddah, KSA',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'fintech-sharjah',
      industry: 'SaaS & Fintech',
      title: 'Customer Onboarding Guidance',
      result: 'AI guides new users through KYC verification, document uploads, and setup steps.',
      challenge: 'Complex onboarding processes cause user drop-off. Support teams are overwhelmed with setup questions.',
      solution: 'Interactive assistant walks users through each step, validates document uploads, and answers setup FAQs.',
      impact: 'Reduced drop-off during onboarding, fewer support tickets, faster time-to-value for new users.',
      metrics: ['Onboarding guidance', 'Fewer support tickets', 'Document validation'],
      iconName: 'Database',
      flag: '🇦🇪',
      location: 'Sharjah, UAE',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'dental-alwakrah',
      industry: 'Healthcare',
      title: 'Appointment Reminder & No-Show Reduction',
      result: 'Automated appointment confirmations, reminders, and waitlist management via WhatsApp.',
      challenge: 'No-show appointments waste doctor time and reduce clinic revenue. Manual reminder calls are time-consuming.',
      solution: 'Automated reminder system sends WhatsApp messages for confirmation, rescheduling, and waitlist fill-in.',
      impact: 'Fewer empty appointment slots, optimized doctor schedules, and reduced manual outreach.',
      metrics: ['Appointment reminders', 'Reduced no-shows', 'Waitlist management'],
      iconName: 'HeartPulse',
      flag: '🇶🇦',
      location: 'Al Wakrah, Qatar',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'spa-salmiya',
      industry: 'Beauty & Wellness',
      title: 'Low-Occupancy Booking Optimization',
      result: 'AI identifies under-booked time slots and offers targeted promotions to fill them.',
      challenge: 'Wellness centers experience low occupancy during weekday mornings, leaving treatment rooms and staff underutilized.',
      solution: 'AI monitors booking patterns and sends personalized offers to past clients for low-occupancy slots.',
      impact: 'Better utilization of staff and rooms during slow periods, increased revenue without additional marketing spend.',
      metrics: ['Targeted slot promotions', 'Increased occupancy', 'Automated offer delivery'],
      iconName: 'Smile',
      flag: '🇰🇼',
      location: 'Salmiya, Kuwait',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'travel-salalah',
      industry: 'Tourism',
      title: 'Tour Booking & Inquiry Handling',
      result: 'AI answers tour availability questions, weather updates, and processes booking requests.',
      challenge: 'Tour operators receive high volumes of inquiries during peak seasons. Slow responses lose potential bookings.',
      solution: 'WhatsApp-based AI assistant answers availability questions, suggests tours, and processes bookings.',
      impact: 'Faster response to inquiries, more bookings captured, and automated voucher delivery.',
      metrics: ['Quick inquiry response', 'Automated booking', 'Digital voucher delivery'],
      iconName: 'Compass',
      flag: '🇴🇲',
      location: 'Salalah, Oman',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'kitchen-dammam',
      industry: 'Food & Beverage',
      title: 'Cloud Kitchen Phone Order Capture',
      result: 'AI answers incoming calls, takes orders, and syncs them directly with the kitchen system.',
      challenge: 'Cloud kitchens lose revenue when phone lines are busy during peak hours and orders go unanswered.',
      solution: 'Voice AI agent answers calls 24/7, takes customer orders, and sends them directly to the kitchen display system.',
      impact: 'Zero missed orders during peak hours, faster order capture, and reduced errors from manual entry.',
      metrics: ['Peak hour order capture', 'Direct kitchen sync', 'Reduced order errors'],
      iconName: 'Utensils',
      flag: '🇸🇦',
      location: 'Dammam, KSA',
      meta: 'Example Scenario — Pilot Phase'
    },
    {
      slug: 'gym-ajman',
      industry: 'Fitness',
      title: 'Membership Renewal Automation',
      result: 'AI reminds members before expiry, sends payment links, and answers facility inquiries.',
      challenge: 'Manual membership renewal outreach takes significant front-desk time. Expired members often lapse without follow-up.',
      solution: 'Automated reminder system sends personalized messages before expiry with payment links and membership details.',
      impact: 'More members renew on time, reduced manual outreach work, and better member retention.',
      metrics: ['Automated renewal reminders', 'Payment link delivery', 'Member inquiry support'],
      iconName: 'Dumbbell',
      flag: '🇦🇪',
      location: 'Ajman, UAE',
      meta: 'Example Scenario — Pilot Phase'
    },
  ] as CaseStudy[],
  ar: [
    {
      slug: 'hotel-doha',
      industry: 'الضيافة',
      title: 'أتمتة مكالمات مكتب استقبال الفنادق',
      result: 'يجيب المساعد الصوتي على مكالمات الضيوف ويتعامل مع طلبات تسجيل الوصول المتأخرة.',
      challenge: 'تستقبل الفنادق أحجاماً كبيرة من المكالمات حول الحجوزات وخدمة الغرف، مما يشتت موظفي الاستقبال.',
      solution: 'يجيب مساعد SAQYN RABT الصوتي على المكالمات ويجمع معلومات الضيف ويوجّه الطلب للقسم المناسب.',
      impact: 'موظفو الاستقبال يقضون وقتاً أقل في المكالمات الروتينية والضيوف يحصلون على ردود أسرع.',
      metrics: ['تقليل عبء المكالمات', 'تغطية 24/7', 'دعم متعدد اللغات'],
      iconName: 'Hotel',
      flag: '🇶🇦',
      location: 'الدوحة، قطر',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'clinic-dubai',
      industry: 'الرعاية الصحية',
      title: 'جدولة مواعيد العيادات',
      result: 'يتولى المساعد استفسارات الحجز ويفرز الحالات العاجلة.',
      challenge: 'يقضي موظفو الاستقبال وقتاً طويلاً في الرد على استفسارات المواعيد.',
      solution: 'مساعد صوتي ذكي يحجز المواعيد ويجيب على الأسئلة الشائعة.',
      impact: 'حجوزات أسرع وتقليل المكالمات الفائتة.',
      metrics: ['حجز مواعيد أسرع', 'مكالمات فائتة أقل', 'فرز سريع للحالات'],
      iconName: 'Activity',
      flag: '🇦🇪',
      location: 'دبي، الإمارات',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'hvac-kuwait',
      industry: 'الخدمات المنزلية',
      title: 'استجابة طوارئ بعد ساعات العمل',
      result: 'يجيب المساعد على مكالمات الطوارئ ويُفعّل توجيه الفني تلقائياً.',
      challenge: 'تفوت شركات الخدمات المنزلية مكالمات الطوارئ بعد ساعات العمل.',
      solution: 'مساعد صوتي يجيب على المكالمات 24/7 ويلتقط تفاصيل الموقع.',
      impact: 'صفر مكالمات فائتة وأوقات استجابة أسرع.',
      metrics: ['التقاط مكالمات 24/7', 'توجيه آلي', 'إيرادات ضائعة أقل'],
      iconName: 'Wrench',
      flag: '🇰🇼',
      location: 'الكويت، الكويت',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'realestate-riyadh',
      industry: 'العقارات',
      title: 'تأهيل استفسارات العقارات',
      result: 'يجيب المساعد على استفسارات المشترين ويسجل التفضيلات ويحجز المعاينات.',
      challenge: 'استفسارات العقارات تصل عبر الهاتف وواتساب، والرد البطيء يسبب فقدان المشترين.',
      solution: 'مساعد ذكي يرد فوراً ويطرح أسئلة تأهيلية.',
      impact: 'رد فوري وتأهيل أفضل قبل إشراك الوكيل.',
      metrics: ['رد فوري', 'تأهيل العملاء', 'جدولة معاينات آلية'],
      iconName: 'Home',
      flag: '🇸🇦',
      location: 'الرياض، السعودية',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'ecommerce-abudhabi',
      industry: 'التجارة الإلكترونية',
      title: 'أتمتة دعم واتساب',
      result: 'يتحقق العملاء من حالة الطلب والمرتجعات عبر مساعد واتساب آلي.',
      challenge: 'استفسارات تتبع الطلبات تغمر فريق الدعم.',
      solution: 'مساعد ذكي متصل بنظام إدارة الطلبات عبر واتساب.',
      impact: 'ردود فورية للعملاء وتقليل عبء فريق الدعم.',
      metrics: ['تتبع آلي للطلبات', 'تحديثات فورية', 'دعم 24/7'],
      iconName: 'ShoppingBag',
      flag: '🇦🇪',
      location: 'أبوظبي، الإمارات',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'logistics-alrayyan',
      industry: 'الخدمات اللوجستية',
      title: 'خدمة ذاتية لحالة الشحن',
      result: 'يتحقق العملاء من حالة الشحن ويعيدون جدولة الاستلام عبر مساعد آلي.',
      challenge: 'شركات التوصيل تتلقى مكالمات كثيرة عن حالة الشحن.',
      solution: 'مساعد خدمة ذاتية متصل بنظام التتبع.',
      impact: 'عبء دعم أقل وإجابات فورية للعملاء.',
      metrics: ['استفسارات ذاتية', 'مكالمات دعم أقل', 'التحقق من العناوين'],
      iconName: 'Truck',
      flag: '🇶🇦',
      location: 'الريان، قطر',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'legal-manama',
      industry: 'الخدمات القانونية',
      title: 'تأهيل الاستشارات القانونية',
      result: 'يفرز المساعد العملاء المحتملين ويسجل تفاصيل القضية.',
      challenge: 'مكاتب المحاماة تفوت مكالمات استشارة بعد ساعات العمل.',
      solution: 'مساعد آمن يجيب على المكالمات 24/7 ويسجل تفاصيل القضية.',
      impact: 'التقاط مكالمات أكثر وتأهيل أفضل للعملاء.',
      metrics: ['التقاط مكالمات بعد الدوام', 'تأهيل الاستشارات', 'جدولة آلية'],
      iconName: 'Briefcase',
      flag: '🇧🇭',
      location: 'المنامة، البحرين',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'rental-muscat',
      industry: 'السيارات',
      title: 'أتمتة حجوزات تأجير السيارات',
      result: 'يعالج المساعد طلبات الإيجار ويؤكد الحجوزات تلقائياً.',
      challenge: 'طوابير طويلة في مكاتب التأجير خلال مواسم السياحة.',
      solution: 'مساعد ذكي يتعامل مع استفسارات الحجز ويسجل بيانات العميل.',
      impact: 'خدمة أسرع وحجوزات أكثر دون موظفين إضافيين.',
      metrics: ['عملية حجز آلية', 'خدمة أسرع', 'توثيق رقمي'],
      iconName: 'Car',
      flag: '🇴🇲',
      location: 'مسقط، عمان',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'education-jeddah',
      industry: 'التعليم',
      title: 'أتمتة استفسارات الطلاب',
      result: 'يجيب المساعد على استفسارات الجداول والمساقات.',
      challenge: 'الموظفون الإداريون يقضون ساعات في الرد على أسئلة متكررة.',
      solution: 'مساعد أكاديمي يجيب على الأسئلة الشائعة عن الجداول والتسجيل.',
      impact: 'ردود فورية للطلاب خارج ساعات الدوام.',
      metrics: ['أتمتة الأسئلة الشائعة', 'دعم بعد الدوام', 'مكالمات إدارية أقل'],
      iconName: 'GraduationCap',
      flag: '🇸🇦',
      location: 'جدة، السعودية',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'fintech-sharjah',
      industry: 'الشركات الناشئة',
      title: 'إرشاد تسجيل العملاء الجدد',
      result: 'يرشد المساعد المستخدمين الجدد خلال خطوات التسجيل.',
      challenge: 'عمليات التسجيل المعقدة تسبب تسرب المستخدمين.',
      solution: 'مساعد تفاعلي يوجّه المستخدم خطوة بخطوة.',
      impact: 'تسرب أقل وتذاكر دعم أقل.',
      metrics: ['إرشاد التسجيل', 'تذاكر دعم أقل', 'التحقق من المستندات'],
      iconName: 'Database',
      flag: '🇦🇪',
      location: 'الشارقة، الإمارات',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'dental-alwakrah',
      industry: 'الرعاية الصحية',
      title: 'تذكير المواعيد وتقليل الغيابات',
      result: 'تأكيدات وتذكيرات آلية للمواعيد عبر واتساب.',
      challenge: 'غياب المرضى يهدر وقت الأطباء ويقلل إيرادات العيادة.',
      solution: 'نظام تذكير آلي يرسل رسائل تأكيد وإعادة جدولة.',
      impact: 'مواعيد فارغة أقل وجداول أطباء محسّنة.',
      metrics: ['تذكير المواعيد', 'غيابات أقل', 'إدارة قائمة الانتظار'],
      iconName: 'HeartPulse',
      flag: '🇶🇦',
      location: 'الوكرة، قطر',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'spa-salmiya',
      industry: 'العناية والجمال',
      title: 'تحسين حجوزات أوقات الركود',
      result: 'يحدد المساعد أوقات الإشغال المنخفض ويقدم عروضاً مخصصة.',
      challenge: 'مراكز العناية تعاني من إشغال منخفض في أيام الأسبوع.',
      solution: 'مساعد يراقب أنماط الحجز ويرسل عروضاً مخصصة.',
      impact: 'استغلال أفضل للمرافق والموظفين.',
      metrics: ['عروض مستهدفة', 'إشغال أعلى', 'توصيل عروض آلي'],
      iconName: 'Smile',
      flag: '🇰🇼',
      location: 'السالمية، الكويت',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'travel-salalah',
      industry: 'السياحة',
      title: 'حجز الرحلات والاستفسارات',
      result: 'يجيب المساعد عن توفر الرحلات ويعالج طلبات الحجز.',
      challenge: 'ضغط الاستفسارات في مواسم الذروة يفوت حجوزات محتملة.',
      solution: 'مساعد عبر واتساب يجيب عن التوفر ويقترح رحلات.',
      impact: 'استجابة أسرع وحجوزات أكثر.',
      metrics: ['رد سريع', 'حجز آلي', 'تسليم قسائم رقمي'],
      iconName: 'Compass',
      flag: '🇴🇲',
      location: 'صلالة، عمان',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'kitchen-dammam',
      industry: 'الأغذية والمشروبات',
      title: 'التقاط طلبات الهاتف للمطابخ السحابية',
      result: 'يجيب المساعد على المكالمات ويسجل الطلبات ويرسلها للمطبخ.',
      challenge: 'المطابخ السحابية تفقد إيرادات في ساعات الذروة.', 
      solution: 'مساعد صوتي يرد 24/7 ويسجل الطلبات ويرسلها للمطبخ.',
      impact: 'صفر طلبات ضائعة في ساعات الذروة.',
      metrics: ['التقاط طلبات الذروة', 'مزامنة المطبخ', 'أخطاء أقل'],
      iconName: 'Utensils',
      flag: '🇸🇦',
      location: 'الدمام، السعودية',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
    {
      slug: 'gym-ajman',
      industry: 'اللياقة البدنية',
      title: 'أتمتة تجديد العضويات',
      result: 'يذكر المساعد الأعضاء قبل انتهاء الاشتراك ويرسل روابط الدفع.',
      challenge: 'متابعة تجديد العضويات يدوياً تستهلك وقت موظفي الاستقبال.',
      solution: 'نظام تذكير آلي برسائل مخصصة وروابط دفع.',
      impact: 'تجديد أكثر وعبء يدوي أقل.',
      metrics: ['تذكير بالتجديد', 'روابط دفع آلية', 'دعم الأعضاء'],
      iconName: 'Dumbbell',
      flag: '🇦🇪',
      location: 'عجمان، الإمارات',
      meta: 'سيناريو مثال — مرحلة تجريبية'
    },
  ] as CaseStudy[],
};
