export interface CaseStudy {
  slug: string;
  industry: string;
  title: string;
  result: string;
  challenge: string;
  solution: string;
  impact: string;
  metrics: string[];
  iconName: string;
  flag: string;
  location: string;
  meta: string;
}

export const cases = {
  en: [
    {
      slug: 'hotel-doha',
      industry: 'Hospitality',
      title: '5-Star Hotel Cuts Front-Desk Calls by 60%',
      result: 'Automated late check-ins, room service requests, and complaint routing. Staff now focus on guest experience instead of phone duty.',
      challenge: 'Doha\'s high tourist arrivals during peak winter season led to 900+ front-desk calls daily, causing long waiting times, staff burnout, and missed guest requests.',
      solution: 'Deployed SAQYN RABT AI virtual voice receptionist to answer room bookings, room service requests, and housekeeping queries in multiple languages.',
      impact: 'Replaced 12 staff hours daily, reduced front-desk calls by 60%, and elevated guest satisfaction ratings to 4.8 stars.',
      metrics: ['60% fewer front-desk calls', '4.8 Star guest satisfaction', '24/7 call coverage'],
      iconName: 'Hotel',
      flag: '🇶🇦',
      location: 'Doha, Qatar',
      meta: '450 Rooms • 12 Staff Saved'
    },
    {
      slug: 'clinic-dubai',
      industry: 'Healthcare',
      title: 'Private Clinic in Dubai Handles 2× Patient Intake',
      result: 'AI answers booking inquiries, triages urgent cases, and routes prescriptions to the pharmacy — all without a receptionist.',
      challenge: 'Medical receptionists spent 75% of their shifts answering basic questions about doctor availability and directions, delaying patient check-ins.',
      solution: 'Integrated a secure, HIPAA-compliant patient intake assistant that schedules appointments and updates EHR records automatically.',
      impact: 'Intake volume doubled instantly, booking times fell under 2 minutes, and medical staff focused purely on clinical operations.',
      metrics: ['2× patient intake', 'Zero missed calls', '15-min avg response time'],
      iconName: 'Activity',
      flag: '🇦🇪',
      location: 'Dubai, UAE',
      meta: '12 Doctors • 24/7 Triage'
    },
    {
      slug: 'hvac-kuwait',
      industry: 'Home Services',
      title: 'Kuwait HVAC Company Captures Every Lead',
      result: 'Emergency calls are answered by AI, dispatch is triggered automatically, and technicians arrive on time every time.',
      challenge: 'High summer temperatures caused emergency booking spikes, leaving 35% of after-hours repair calls unanswered.',
      solution: 'Integrated SAQYN RABT voice agents to answer emergency repair calls, verify warranties, and dispatch technicians via SMS integration.',
      impact: 'Captured 100% of after-hours calls, lowered dispatch times to 30 minutes, and grew service revenue by 40%.',
      metrics: ['Full lead capture', '30-min avg dispatch', '40% revenue increase'],
      iconName: 'Wrench',
      flag: '🇰🇼',
      location: 'Kuwait City, Kuwait',
      meta: '25 Technicians • 0% Lead Waste'
    },
    {
      slug: 'realestate-riyadh',
      industry: 'Real Estate',
      title: 'Property Firm Automates Lead Response within 60s',
      result: 'AI answers buyer queries, qualifies leads based on budget, and schedules viewing sessions with agents automatically.',
      challenge: 'High volume of property inquiries on WhatsApp went unanswered for hours, causing buyer drop-off during peak property listings.',
      solution: 'Configured AI real estate agents to pre-qualify buyer budgets and instantly schedule villa viewings on agents\' calendars.',
      impact: 'Achieved sub-60s response times and boosted sales conversion by 3.8×.',
      metrics: ['60-second response time', '3.8× conversion boost', 'Automated agent scheduling'],
      iconName: 'Home',
      flag: '🇸🇦',
      location: 'Riyadh, KSA',
      meta: '1,500+ Properties • Instant Qualify'
    },
    {
      slug: 'ecommerce-abudhabi',
      industry: 'E-commerce',
      title: 'Retailer Automates WhatsApp Support, Conversion up 35%',
      result: 'Automated order status checking, returns management, and personalized checkout reminders via WhatsApp Business API.',
      challenge: 'Order verification and return requests overloaded the support team, causing delayed shipments and customer disputes.',
      solution: 'Connected the WhatsApp Business API with SAQYN RABT to automate order tracking, status checks, and return label generation.',
      impact: 'Decreased customer support backlog to zero, automating 90% of order queries and lifting conversion by 35%.',
      metrics: ['35% conversion increase', '90% automated support', '24/7 tracking availability'],
      iconName: 'ShoppingBag',
      flag: '🇦🇪',
      location: 'Abu Dhabi, UAE',
      meta: '40k Monthly Orders • Zero Backlog'
    },
    {
      slug: 'logistics-alrayyan',
      industry: 'Logistics',
      title: 'Delivery Firm Cuts Support Workload by 45%',
      result: 'Customers check delivery status, schedule pickups, and resolve address issues instantly through an automated web agent.',
      challenge: 'Address discrepancies and pickup scheduling calls caused delivery delays during peak holiday seasons.',
      solution: 'Implemented a web-based address correction agent that updates courier navigation routes dynamically.',
      impact: 'Cut support workload by 45% and reduced incorrect delivery drop-offs to near zero.',
      metrics: ['45% support workload cut', '99% address verification', '12-sec average load'],
      iconName: 'Truck',
      flag: '🇶🇦',
      location: 'Al Rayyan, Qatar',
      meta: '150 Delivery Vehicles • Real-time status'
    },
    {
      slug: 'legal-manama',
      industry: 'Legal Services',
      title: 'Law Firm Captures 40% More Consultation Bookings',
      result: 'AI handles intake filtering, queries legal specializations, and books qualified consultations directly to lawyers calendars.',
      challenge: 'Client intakes after 5 PM went to voicemail, leading prospective clients to seek competitors instead.',
      solution: 'Set up a secure intake assistant to screen legal specialities, check attorney conflict of interest, and book consultations.',
      impact: 'Captured 40% more intake consultation requests and automated calendar sync for 8 senior law partners.',
      metrics: ['40% more consultations', '100% HIPAA/Privacy compliant', 'Instant intake filtering'],
      iconName: 'Briefcase',
      flag: '🇧🇭',
      location: 'Manama, Bahrain',
      meta: '8 Partners • Zero missed legal intakes'
    },
    {
      slug: 'rental-muscat',
      industry: 'Automotive',
      title: 'Muscat Car Rental Agency Cuts Booking Time by 70%',
      result: 'AI scans driver licenses, processes rental requests, and routes billing details to payments backend automatically.',
      challenge: 'High tourist load at Muscat Airport delayed counter checkout paperwork, leading to customer frustration.',
      solution: 'Deployed AI agents to process driver license verification, scan passports, and handle rental contracts.',
      impact: 'Reduced counter checkout booking time by 70% and processed airport rentals fully digitally.',
      metrics: ['70% booking time saved', 'Instant license scan', '85% repeat customers'],
      iconName: 'Car',
      flag: '🇴🇲',
      location: 'Muscat, Oman',
      meta: '250 Vehicles • Fully digital intake'
    },
    {
      slug: 'education-jeddah',
      industry: 'Education',
      title: 'Jeddah Institute Automatically Coordinates 1,500 Students',
      result: 'AI acts as a study assistant, answers schedule queries, and manages student onboarding processes for multiple campuses.',
      challenge: 'Academic inquiries about class schedules, course materials, and exams overloaded administrative staff.',
      solution: 'Deployed a virtual campus assistant on the student portal to answer curriculum FAQs and class schedules.',
      impact: 'Admin calls fell by 80%, coordinating course notifications for 1,500 students seamlessly.',
      metrics: ['1,500 students supported', '80% fewer admin calls', 'Instant schedule checks'],
      iconName: 'GraduationCap',
      flag: '🇸🇦',
      location: 'Jeddah, KSA',
      meta: '3 Campuses • Multi-course coordination'
    },
    {
      slug: 'fintech-sharjah',
      industry: 'SaaS & Fintech',
      title: 'Sharjah Startup Reduces Onboarding Friction by 50%',
      result: 'AI guides new business customers through KYC verification, documentation checks, and setup queries automatically.',
      challenge: 'Complex corporate KYC verification caused a 40% user drop-off rate during signup due to document guidelines.',
      solution: 'Created an interactive walkthrough assistant to check KYC documentation upload status and answer setup queries.',
      impact: 'Slashed corporate customer onboarding drop-offs by half and reduced customer queries by 50%.',
      metrics: ['50% friction reduction', 'Instant KYC checklist guidance', '24/7 technical setup'],
      iconName: 'Database',
      flag: '🇦🇪',
      location: 'Sharjah, UAE',
      meta: 'B2B Client Portal • Secure sandbox guidance'
    },
    {
      slug: 'dental-alwakrah',
      industry: 'Healthcare',
      title: 'Al Wakrah Dental Center Cuts No-Shows by 80%',
      result: 'Automated appointment confirmation, late cancellation warnings, and standby queue routing over WhatsApp.',
      challenge: 'Patient appointment no-shows led to empty surgery rooms, reducing dental doctor utilization rates.',
      solution: 'Set up an automated reminder system on WhatsApp that allows patients to confirm, reschedule, or standby.',
      impact: 'Reduced dental center appointment no-shows by 80% and kept daily schedules fully optimized.',
      metrics: ['80% fewer no-shows', 'Full standby queue fill', '98% patient feedback'],
      iconName: 'HeartPulse',
      flag: '🇶🇦',
      location: 'Al Wakrah, Qatar',
      meta: '5 Surgery Rooms • 24/7 Standby routing'
    },
    {
      slug: 'spa-salmiya',
      industry: 'Beauty & Wellness',
      title: 'Salmiya Spa Increases Weekday Bookings by 30%',
      result: 'AI targets low-occupancy slots, proposes custom weekday packages, and handles reservations instantly.',
      challenge: 'Under-utilized spa treatment rooms during weekday mornings resulted in lost operational revenue.',
      solution: 'Deployed a marketing agent that detects low-occupancy slots and texts discount booking offers.',
      impact: 'Boosted weekday morning bookings by 30% and filled therapist calendars.',
      metrics: ['30% more weekday bookings', 'Automated package upsell', 'Zero double bookings'],
      iconName: 'Smile',
      flag: '🇰🇼',
      location: 'Salmiya, Kuwait',
      meta: '12 Treatment Rooms • Occupancy target focus'
    },
    {
      slug: 'travel-salalah',
      industry: 'Tourism',
      title: 'Salalah Tour Operator Boosts Bookings 2.5×',
      result: 'AI answers queries about tour availability, local weather updates, and automates hotel booking voucher delivery.',
      challenge: 'Inquiries about local tour availability during Salalah Khareef season overwhelmed the agency.',
      solution: 'Automated WhatsApp tour booking agents to process reservations and dispatch tour guides.',
      impact: 'Multiplied package bookings by 2.5× and automated ticket delivery processes.',
      metrics: ['2.5× booking increase', 'Automated voucher delivery', 'Multi-language translation'],
      iconName: 'Compass',
      flag: '🇴🇲',
      location: 'Salalah, Oman',
      meta: 'Khareef Season Specialist • Instant dispatch'
    },
    {
      slug: 'kitchen-dammam',
      industry: 'Food & Beverage',
      title: 'Dammam Cloud Kitchen Network Automates Phone Orders',
      result: 'AI answers high-volume customer orders, queries diet preferences, and syncs directly with kitchen POS terminals.',
      challenge: 'High peak dinner order volumes caused busy phone lines and missed order revenue.',
      solution: 'Implemented voice AI order agents integrated with kitchen POS terminals to capture calls.',
      impact: 'Answered 95% of incoming calls and routed orders to POS terminals with zero input errors.',
      metrics: ['95% call answer rate', 'Direct kitchen POS sync', 'Zero order input error'],
      iconName: 'Utensils',
      flag: '🇸🇦',
      location: 'Dammam, KSA',
      meta: '8 Kitchen Hubs • 5,000 Orders/day'
    },
    {
      slug: 'gym-ajman',
      industry: 'Fitness',
      title: 'Ajman Gym Chain Automates Membership Renewals by 90%',
      result: 'AI reminds members before expiry, manages payment links, and answers gym facility hours and trainer queries.',
      challenge: 'Manual renewal outreach took hours of front desk staff time, causing membership leaks.',
      solution: 'Configured renewal payment reminder agents that text payment link vouchers.',
      impact: 'Automated 90% of gym membership renewals and reduced membership drop-offs.',
      metrics: ['90% renewal automation', 'Instant billing links', '24/7 member inquiry answers'],
      iconName: 'Dumbbell',
      flag: '🇦🇪',
      location: 'Ajman, UAE',
      meta: '4 Locations • 3,200 Members supported'
    },
  ] as CaseStudy[],
  ar: [
    {
      slug: 'hotel-doha',
      industry: 'الضيافة',
      title: 'فندق 5 نجوم يخفض مكالمات مكتب الاستقبال بنسبة 60%',
      result: 'أتمتة تسجيلات الوصول المتأخرة وطلبات خدمة الغرف وتوجيه الشكاوى. يركز الموظفون الآن على تجربة الضيوف بدلاً من الهاتف.',
      challenge: 'أدت مواسم الأعياد المزدحمة إلى استقبال أكثر من 900 مكالمة يومياً في الاستقبال، مما أدى إلى فترات انتظار طويلة وضغط على الموظفين.',
      solution: 'نشر موظف استقبال مدعوم بالذكاء الاصطناعي من SAQYN RABT للتعامل مع استفسارات خدمة الغرف ومواعيد المغادرة وتوجيه الشكاوى.',
      impact: 'انخفض حجم المكالمات بنسبة 60% في أول أسبوعين، مما وفر 12 ساعة عمل يومية للموظفين ورفع رضا النزلاء إلى 4.8 نجوم.',
      metrics: ['60% مكالمات أقل لمكتب الاستقبال', '4.8 رضا النزلاء', 'تغطية مكالمات 24/7'],
      iconName: 'Hotel',
      flag: '🇶🇦',
      location: 'الدوحة، قطر',
      meta: '450 غرفة • توفير 12 موظفاً'
    },
    {
      slug: 'clinic-dubai',
      industry: 'الرعاية الصحية',
      title: 'عيادة خاصة في دبي تعالج ضعف عدد المرضى',
      result: 'يجيب الذكاء الاصطناعي على استفسارات الحجز ويفرز الحالات العاجلة ويوجه الوصفات إلى الصيدلية — كل ذلك بدون موظف استقبال.',
      challenge: 'قضى موظفو الاستقبال 75% من وقتهم في الإجابة على أسئلة حول مواعيد الأطباء والاتجاهات، مما عطل رعاية المرضى.',
      solution: 'تهيئة مساعد حجز ذكي متوافق بالكامل مع معايير الأمان وجدولة المواعيد وتحديث السجلات الطبية.',
      impact: 'تضاعف عدد الحجوزات الطبية فوراً، وأصبح المرضى يحجزون في أقل من دقيقتين، وتفرغ الاستقبال لمساعدة الحالات الحرجة.',
      metrics: ['ضعف عدد المرضى', 'صفر مكالمات فائتة', 'متوسط وقت الرد 15 دقيقة'],
      iconName: 'Activity',
      flag: '🇦🇪',
      location: 'دبي، الإمارات',
      meta: '12 طبيب • فرز حالات 24/7'
    },
    {
      slug: 'hvac-kuwait',
      industry: 'الخدمات المنزلية',
      title: 'شركة تكييف كويتية تلتقط كل العملاء المحتملين',
      result: 'يجيب الذكاء الاصطناعي على مكالمات الطوارئ، ويتم تفعيل التوجيه تلقائياً، ويصل الفنيون في الوقت المحدد في كل مرة.',
      metrics: ['التقاط كامل للعملاء المحتملين', 'متوسط التوجيه 30 دقيقة', 'زيادة الإيرادات 40%'],
      challenge: 'خلال أشهر الصيف الحارة، لم يتم الرد على 35% من مكالمات الطوارئ بعد الساعة 6 مساءً، مما كلف آلاف الدنانير كإيرادات ضائعة.',
      solution: 'ربط وكلاء الصوت الذكي من SAQYN RABT للرد على مكالمات الطوارئ، والتحقق من الضمان وتوجيه الفني الأقرب عبر الرسائل النصية.',
      impact: 'التقاط كامل لجميع اتصالات الطوارئ، وتقليل وقت وصول الفني إلى 30 دقيقة، مع زيادة 40% في الإيرادات الإجمالية.',
      iconName: 'Wrench',
      flag: '🇰🇼',
      location: 'الكويت، الكويت',
      meta: '25 فني • 0% ضياع عملاء'
    },
    {
      slug: 'realestate-riyadh',
      industry: 'العقارات',
      title: 'شركة عقارية تؤتمت الرد على العملاء خلال 60 ثانية',
      result: 'يجيب الذكاء الاصطناعي على استفسارات المشترين، ويؤهلهم حسب الميزانية، وينظم مواعيد المعاينة مع الوكلاء تلقائياً.',
      challenge: 'واجهت الشركة تأخيراً كبيراً في الرد على استفسارات المشترين مما أدى إلى ضياع صفقات عقارية هامة.',
      solution: 'تهيئة عميل عقاري ذكي للفرز الأولي والتأهيل السريع للمشترين ثم جدولة مواعيد المعاينات تلقائياً.',
      impact: 'تقديم رد فوري للمشترين في أقل من دقيقة مع زيادة نسب تحويل المبيعات بمعدل 3.8 ضعف.',
      metrics: ['رد في 60 ثانية', 'زيادة التحويلات 3.8 ضعف', 'مواعيد معاينة مؤتمتة'],
      iconName: 'Home',
      flag: '🇸🇦',
      location: 'الرياض، السعودية',
      meta: '1,500+ عقار • تأهيل فوري'
    },
    {
      slug: 'ecommerce-abudhabi',
      industry: 'التجارة الإلكترونية',
      title: 'متجر تجزئة يؤتمت دعم واتساب ويرفع التحويل 35%',
      result: 'تتبع الطلبات المؤتمت، وإدارة المرتجعات، وتذكير السلات المتروكة بشكل مخصص عبر واتساب بيزنس.',
      challenge: 'تراكمت اتصالات العملاء للاستفسار عن الشحن ومشاكل الإرجاع مما عطل فريق الدعم.',
      solution: 'ربط واجهة واتساب بيزنس بأتمتة ذكية متكاملة لتتبع مسار الطلبات ومعالجة الشكاوى ذاتياً.',
      impact: 'تصفير تراكم تذاكر الدعم والرد الفوري على 90% من استفسارات العملاء مع زيادة 35% في المبيعات.',
      metrics: ['زيادة التحويل 35%', 'أتمتة الدعم بنسبة 90%', 'تتبع متاح 24/7'],
      iconName: 'ShoppingBag',
      flag: '🇦🇪',
      location: 'أبوظبي، الإمارات',
      meta: '40 ألف طلب شهرياً • صفر تراكم'
    },
    {
      slug: 'logistics-alrayyan',
      industry: 'الخدمات اللوجستية',
      title: 'شركة توصيل تخفض عبء الدعم بنسبة 45%',
      result: 'يتتبع العملاء شحناتهم، ويجدولون مواعيد الاستلام، ويحلون مشاكل العناوين فوراً عبر مساعد ويب ذكي.',
      challenge: 'أدت أخطاء تدوين العناوين وهواتف المستلمين إلى تأخر الشحنات وتزايد شكاوى العملاء.',
      solution: 'إطلاق نظام تحقق تلقائي من صحة العناوين وتعديل مسارات السائقين بذكاء.',
      impact: 'تخفيض حجم المكالمات لمركز الدعم بنسبة 45% مع تفادي أخطاء تسليم الشحنات تماماً.',
      metrics: ['خفض الدعم بنسبة 45%', 'تحقق من العناوين 99%', 'متوسط تحميل 12 ثانية'],
      iconName: 'Truck',
      flag: '🇶🇦',
      location: 'الريان، قطر',
      meta: '150 سيارة توصيل • حالة شحن فورية'
    },
    {
      slug: 'legal-manama',
      industry: 'الخدمات القانونية',
      title: 'مكتب محاماة يلتقط 40% أكثر من حجوزات الاستشارات',
      result: 'يقوم الذكاء الاصطناعي بفرز الاستفسارات وتحديد الاختصاصات وحجز الاستشارات مباشرة على تقويم المحامين.',
      challenge: 'ضياع العديد من العملاء الجدد لعدم الرد على اتصالاتهم بعد ساعات العمل الرسمية للمكتب.',
      solution: 'تصميم نظام فرز قانوني آمن ومطابق بالكامل للسرية لتأهيل القضايا وجدولة جلسات الاستشارة.',
      impact: 'التقاط 40% استشارات إضافية شهرياً وتنسيق الجداول لثمانية محامين شركاء دون تداخل.',
      metrics: ['40% استشارات أكثر', 'متوافق مع الخصوصية 100%', 'فرز فوري للطلبات'],
      iconName: 'Briefcase',
      flag: '🇧🇭',
      location: 'المنامة، البحرين',
      meta: '8 شركاء • صفر ضياع طلبات استشارة'
    },
    {
      slug: 'rental-muscat',
      industry: 'السيارات',
      title: 'وكالة تأجير سيارات بمسقط تخفض وقت الحجز 70%',
      result: 'يقوم المساعد بمسح رخص القيادة ضوئياً، ومعالجة طلبات الإيجار، وتوجيه بيانات الدفع تلقائياً.',
      challenge: 'طول طوابير الانتظار لإنهاء المعاملات اليدوية في مطار مسقط الدولي وإزعاج الزوار.',
      solution: 'دمج تقنية مسح المستندات وتأكيد العقود والدفع بشكل ذاتي ورقمي.',
      impact: 'تقليص وقت إنهاء إجراءات الحجز بنسبة 70% وتأجير السيارات بالكامل بطرق لا تلامسية.',
      metrics: ['توفير 70% من وقت الحجز', 'مسح رخصة فوري', '85% عملاء متكررين'],
      iconName: 'Car',
      flag: '🇴🇲',
      location: 'مسقط، عمان',
      meta: '250 مركبة • تسجيل رقمي بالكامل'
    },
    {
      slug: 'education-jeddah',
      industry: 'التعليم',
      title: 'معهد بجدة ينسق شؤون 1,500 طالب تلقائياً',
      result: 'مساعد تعليمي ذكي يجيب على استفسارات الجداول الدراسية وينظم عملية تسجيل الطلاب للفروع المتعددة.',
      challenge: 'الضغط الإداري العالي للإجابة على استفسارات الطلاب المتكررة حول المحاضرات والامتحانات.',
      solution: 'إدخال مساعد أكاديمي على مدار الساعة على منصة المعهد للإجابة الفورية وتحديث المواعيد.',
      impact: 'تخفيض المكالمات الإدارية بنسبة 80% وخدمة وتنسيق جداول 1,500 طالب في 3 فروع.',
      metrics: ['مساعدة 1,500 طالب', 'مكالمات إدارية أقل 80%', 'فحص فوري للجداول'],
      iconName: 'GraduationCap',
      flag: '🇸🇦',
      location: 'جدة، السعودية',
      meta: '3 فروع • تنسيق مساقات متعددة'
    },
    {
      slug: 'fintech-sharjah',
      industry: 'الشركات الناشئة',
      title: 'شركة ناشئة بالشارقة تخفض عوائق التسجيل 50%',
      result: 'يساعد الذكاء الاصطناعي العملاء في خطوات التحقق من الهوية، وفحص المستندات، واستفسارات الإعداد.',
      challenge: 'نسبة ارتداد عالية للشركات أثناء عملية التسجيل وتوثيق الحسابات بسبب التعقيد.',
      solution: 'تصميم مساعد تفاعلي يرشد المستخدم خطوة بخطوة ويرد على استفسارات رفع الأوراق الثبوتية.',
      impact: 'تخفيض نسبة التخلي عن الحسابات بمعدل النصف وتسريع تفعيل الشركات بنسبة 50%.',
      metrics: ['خفض عوائق التسجيل 50%', 'مساعدة فورية بمتطلبات الهوية', 'إعداد تقني 24/7'],
      iconName: 'Database',
      flag: '🇦🇪',
      location: 'الشارقة، الإمارات',
      meta: 'بوابة عملاء B2B • مساعدة إعداد آمنة'
    },
    {
      slug: 'dental-alwakrah',
      industry: 'الرعاية الصحية',
      title: 'مركز طب أسنان بالوكرة يخفض الغيابات بنسبة 80%',
      result: 'تأكيد المواعيد المؤتمت، وتنبيهات الإلغاء المتأخر، وجدولة طابور الانتظار عبر واتساب.',
      challenge: 'تأثير إلغاء المواعيد المفاجئ والغياب على فترات حجز الأطباء التشغيلية.',
      solution: 'بناء نظام تنبيه ومتابعة ذكي على واتساب مع جدولة فورية للعملاء بقائمة الانتظار.',
      impact: 'الحد من غيابات المرضى بنسبة 80% وملء الفراغات الطارئة في جدول الأطباء تلقائياً.',
      metrics: ['غيابات أقل بنسبة 80%', 'ملء طابور الاحتياط بالكامل', '98% تقييم المرضى'],
      iconName: 'HeartPulse',
      flag: '🇶🇦',
      location: 'الوكرة، قطر',
      meta: '5 غرف علاج • تنظيم طابور انتظار 24/7'
    },
    {
      slug: 'spa-salmiya',
      industry: 'العناية والجمال',
      title: 'سبا بالسالمية يرفع حجوزات أيام الأسبوع بنسبة 30%',
      result: 'يستهدف الذكاء الاصطناعي الأوقات ذات الإشغال المنخفض، ويعرض باقات مخصصة، وينجز الحجز فوراً.',
      challenge: 'تدني مستويات الإشغال والحجوزات لخدمات السبا في فترات منتصف الأسبوع.',
      solution: 'إطلاق حملات تفاعلية ذكية ترسل عروضاً مخصصة في فترات الركود وجدولتها ذاتياً.',
      impact: 'رفع الحجوزات في أيام العمل العادية بنسبة 30% مع الاستخدام الأمثل لموارد المركز.',
      metrics: ['حجوزات أكثر 30%', 'عرض باقات مكملة مؤتمت', 'صفر حجوزات مزدوجة'],
      iconName: 'Smile',
      flag: '🇰🇼',
      location: 'السالمية، الكويت',
      meta: '12 غرفة علاج • تركيز على فترات الركود'
    },
    {
      slug: 'travel-salalah',
      industry: 'السياحة',
      title: 'منظم رحلات بصلالة يضاعف الحجوزات 2.5 مرة',
      result: 'يجيب الذكاء الاصطناعي على استفسارات الرحلات وأحوال الطقس، ويؤتمت إرسال قسائم الفنادق.',
      challenge: 'الضغط الهائل للاستفسارات عن رحلات خريف صلالة وصعوبة الاستجابة للجميع في نفس الوقت.',
      solution: 'تصميم مساعد رحلات ذكي بلغات متعددة يجيب على تفاصيل الطقس وتوافر الرحلات والتسجيل.',
      impact: 'مضاعفة الحجوزات 2.5 مرة مع إرسال فوري ومؤتمت بالكامل لجميع تذاكر وقسائم الرحلات.',
      metrics: ['زيادة الحجوزات 2.5 ضعف', 'تسليم قسائم مؤتمت', 'ترجمة لغات متعددة'],
      iconName: 'Compass',
      flag: '🇴🇲',
      location: 'صلالة، عمان',
      meta: 'مختص بموسم الخريف • إرسال فوري للقسائم'
    },
    {
      slug: 'kitchen-dammam',
      industry: 'الأغذية والمشروبات',
      title: 'مطبخ سحابي بالدمام يؤتمت طلبات الهاتف',
      result: 'يجيب المساعد على مكالمات الطلبات المرتفعة، ويسجل الملاحظات الغذائية، ويزامنها مع نظام المطبخ.',
      challenge: 'فقدان طلبات هاتفية هامة للعملاء في ساعات العشاء المزدحمة لعدم توافر خطوط كافية.',
      solution: 'نشر مساعد طلبات صوتي ذكي يربط الطلب مباشرة بنظام التشغيل POS بالمطابخ.',
      impact: 'استجابة للمكالمات بنسبة 95% وتفادي أخطاء تدوين الطلبات مع المزامنة الفورية للمطابخ.',
      metrics: ['إجابة مكالمات 95%', 'مزامنة فورية مع الكاشير', 'صفر أخطاء في تدوين الطلبات'],
      iconName: 'Utensils',
      flag: '🇸🇦',
      location: 'الدمام، السعودية',
      meta: '8 مطابخ مركزية • 5,000 طلب يومياً'
    },
    {
      slug: 'gym-ajman',
      industry: 'اللياقة البدنية',
      title: 'نادي رياضي بعجمان يؤتمت تجديد الاشتراكات بنسبة 90%',
      result: 'يذكر المساعد الأعضاء قبل انتهاء الاشتراك، ويدير روابط الدفع، ويجيب على مواعيد الحصص.',
      challenge: 'استهلاك فترات طويلة لمتابعة الأعضاء المنتهية اشتراكاتهم يدوياً مما تسبب في تسرب العملاء.',
      solution: 'إعداد وكلاء تذكير ومتابعة تلقائية عبر رسائل مخصصة تحتوي على روابط تجديد آمنة.',
      impact: 'أتمتة تجديد اشتراكات الأعضاء بنسبة 90% وخفض مستويات التخلي عن التدريب.',
      metrics: ['أتمتة التجديد بنسبة 90%', 'روابط دفع فورية', 'إجابات على أسئلة الأعضاء 24/7'],
      iconName: 'Dumbbell',
      flag: '🇦🇪',
      location: 'عجمان، الإمارات',
      meta: '4 مواقع • مساعدة 3,200 عضو'
    },
  ] as CaseStudy[],
};
