name: Security Scanning (SAST/DAST)

on:
  push:
    branches: [ main ]

jobs:
  sonar_scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=salah77712
            -Dsonar.projectKey=salah77712_saqynrabt
            -Dsonar.sources=frontend,backend-workers
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.next/**,**/.wrangler/**
